<?php

namespace Jawabkom\Backend\Module\Spam\Detection\Test\Unit;

use Jawabkom\Backend\Module\Spam\Detection\Exception\RequiredInputsException;
use Jawabkom\Backend\Module\Spam\Detection\Exception\RequiredPhoneException;
use Jawabkom\Backend\Module\Spam\Detection\InputFilter\SpamPhoneScoreInputsFilter;
use Jawabkom\Backend\Module\Spam\Detection\InputValidator\SpamPhoneScoreInputsValidator;
use Jawabkom\Backend\Module\Spam\Detection\Test\AbstractTestCase;

/**
 * @property SpamPhoneScoreInputsFilter $filterService
 */
class SpamPhoneScoreInputFilterTest extends AbstractTestCase
{

    public function setUp(): void
    {
        $this->filterService = new SpamPhoneScoreInputsFilter();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws RequiredPhoneException
     */
    public function test_must_throw_exception_if_inputs_are_empty() {
        $this->expectException(RequiredInputsException::class);
        $inputs = [];
        $this->filterService->filter($inputs);
    }

    /**
     * @throws RequiredInputsException
     */
    public function test_must_throw_exception_if_phone_is_empty() {
        $this->expectException(RequiredPhoneException::class);
        $inputs = [
            'source' => '', // required
            'country_code' => '', // required, valid country code, 2 letters
            'score' => 0,  // 0 - 100
            'tags' => [], // one dimintional array of strings, or empty
        ];
        $this->filterService->filter($inputs);
    }

    /**
     * @throws RequiredInputsException
     * @throws RequiredPhoneException
     */
    public function test_must_filter_phone_to_proper_format()
    {
        $inputs = [
            'phone' => '+972599189357'
        ];
        $filteredInputs = $this->filterService->filter($inputs);
        $this->assertTrue(true);
    }
}